# Generated by Django 5.2.8 on 2025-11-20 23:51

import django.db.models.deletion
import theatre_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='image',
            field=models.ImageField(null=True, upload_to=theatre_app.models.create_custom_path),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='theatre_app.reservation'),
        ),
    ]
